services:
  app:
    build: .
    volumes:
      - ./:/var/www
    container_name: microframework-app
    working_dir: /var/www
    networks:
      - microframework-network

  database:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./.database/:/var/lib/mysql
    container_name: microframework-database
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microframework-network

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf/:/etc/nginx/conf.d/default.conf
    container_name: microframework-nginx
    networks:
      - microframework-network

networks:
  microframework-network:
    driver: bridge
